### ISSUE TITLE
Error: unrecognized cop or department Standard/BlockSingleLineBraces

### ISSUE THREAD

**Issue by pboling** [standardrb/standard-custom#4]
I did a `bundle update`, and now I'm getting an error:

```
Error: unrecognized cop or department Standard/BlockSingleLineBraces found in /Users/pboling/.asdf/installs/ruby/2.7.8/lib/ruby/gems/2.7.0/gems/standard-custom-1.0.1/config/base.yml
```

The updates were:
```
Fetching lint_roller 1.1.0 (was 1.0.0)
Installing lint_roller 1.1.0 (was 1.0.0)
# ...
Using standard-custom 1.0.1 # <============ NOTE: standard-custom did not get updated.
Fetching standard-performance 1.1.1 (was 1.1.0)
Installing standard-performance 1.1.1 (was 1.1.0)
Fetching standard 1.30.1 (was 1.29.0)
Installing standard 1.30.1 (was 1.29.0)
# ...
```

NOTE: I am not using the standard runtime, I'm only attempting to use the cops and rules.

**Comment by pboling** [comment]
Somehow this gem is locked to:
```
Using rubocop 1.52.1
```

But `standard` is allowing:
```
Using rubocop 1.52.1
```

And I think that is what is allowing the test suite for this gem to pass, even though it doesn't work with latest `standard` release.

**Comment by pboling** [comment]
Ooooh, the locking of rubocop in Gemfile results in loading a months old version of standard!  If I remove the Rubocop lock, it allows Standard to update to latest, which in turn locks handles the RuboCop dependency itself.

```
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Using rake 13.0.6
Using bundler 2.4.10
Using language_server-protocol 3.17.0.3
Using racc 1.7.1
Using rainbow 3.1.1
Using regexp_parser 2.8.1
Using minitest 5.18.1
Using parallel 1.23.0
Using ruby-progressbar 1.13.0
Using unicode-display_width 2.4.2
Using json 2.6.3
Using ast 2.4.2
Using lint_roller 1.1.0
Using rexml 3.2.5
Using method_source 1.0.0
Using parser 3.2.2.3
Using standard-custom 1.0.1 from source at `.`
Using rubocop-ast 1.29.0
Using m 1.6.1
Using rubocop 1.52.1 (was 1.48.1)
Using rubocop-performance 1.18.0 (was 1.16.0)
Fetching standard-performance 1.1.1
Installing standard-performance 1.1.1
Fetching standard 1.30.1 (was 1.26.0)
Installing standard 1.30.1 (was 1.26.0)
Bundle updated!
```

**Comment by pboling** [comment]
Actually this is related to the increasing moves toward the Lint Roller (which is awesome), but now I'm not sure how to load this in a project that is using Standard's Cops & rules without using Standard's runtime.

**Comment by pboling** [comment]
I suppose what I need to figure out is how to run Lint Roller to set up the plugin's Cops, so that the rules are available when the RucoCop configs are loaded.  I expect this is a goal of Lint Roller being a separate project from Standard... I remember last time I looked into it it wasn't immediately clear how it would be done.  It seems like making `rubocop-lts` configure itself with LintRoller might be the solution.

**Comment by pboling** [comment]
The band-aid fix is to:
```
require "standard/cop/block_single_line_braces"
```

in a file somewhere, (e.g. `lib/standard/custom/cops`), and then require that file in the `rubocop.yml`:

```
require:
  - lib/standard/custom/cops
```

That's sufficient for now.

**Comment by searls** [comment]
What was the Gemfile and Gemfile.lock that originated this issue?

Just to clarify: using any of Standard's plugins or rules outside Standard is considered unsupported. (Feel free to do it, but we won't necessarily invest effort triaging/fixing issues that result).

**Comment by pboling** [comment]
@searls I've released a new version of `standard-rubocop-lts` with the fix.  It's essentially my attempt at adding an external layer of support (me supporting myself) for using standard's rules without the runtime.  That's the relevant Gemfile /  gemspec / code.

The way I see it, the rules you've collected are quite useful.  As other linting tools to utilize them, albeit in an unsupported by you, but supported by me, manner, it will benefit the upstream `standard` project (as I've already shown in a bunch of PRs).

https://github.com/rubocop-lts/standard-rubocop-lts/
